# Generated by Django 5.0.1 on 2024-02-11 07:34

import django_resized.forms
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='specifications',
            field=models.JSONField(),
        ),
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=django_resized.forms.ResizedImageField(crop=None, default='user_avatars/avatar_default.jpeg', force_format='JPEG', keep_meta=True, quality=75, scale=0.5, size=[168, 168], upload_to='user_avatars/'),
        ),
        migrations.AlterField(
            model_name='user',
            name='banner',
            field=django_resized.forms.ResizedImageField(crop=None, default='user_avatars/banner_default.jpg', force_format='JPEG', keep_meta=True, quality=75, scale=0.5, size=[1198, 124], upload_to='user_banners/'),
        ),
    ]
