# Generated by Django 5.0.1 on 2024-02-13 14:22

import django_resized.forms
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0005_alter_user_avatar_alter_user_banner'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='verified',
            new_name='is_verified',
        ),
        migrations.AddField(
            model_name='user',
            name='phone_number',
            field=models.CharField(default=1, max_length=25),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=django_resized.forms.ResizedImageField(blank=True, crop=None, default='user_avatars/avatar_default.jpeg', force_format='JPEG', keep_meta=True, null=True, quality=75, scale=0.5, size=[168, 168], upload_to='user_avatars/'),
        ),
        migrations.AlterField(
            model_name='user',
            name='banner',
            field=django_resized.forms.ResizedImageField(blank=True, crop=None, default='user_avatars/banner_default.jpg', force_format='JPEG', keep_meta=True, null=True, quality=75, scale=0.5, size=[1198, 124], upload_to='user_banners/'),
        ),
        migrations.AlterField(
            model_name='user',
            name='intro',
            field=models.TextField(blank=True, max_length=1024, null=True),
        ),
    ]
